### ISSUE TITLE
Build configuration for our project

### ISSUE THREAD

**Issue by VexingTomahawk** [CSC207-UofT/course-project-variable#10]
I think we need a build configuration tool to handle our dependencies for our project, dependencies like Junit and Gson. I've already setup Gradle in one of my branches and it seems to work well.

Let me know what you guys think.

**Comment by tsh4fiq** [comment]
I think that's a great idea, I personally had issues with dependencies when running the GUIBranch so if your Gradle is compatible with the frontend so I think anyone running the project would appreciate it too.
