### ISSUE TITLE
Task and TaskList packaging

### ISSUE THREAD

**Issue by VexingTomahawk** [CSC207-UofT/course-project-variable#20]
Where should we put Task and TaskList in the packaging structure? From the feedback, the TA said they are currently in an awkward place.

I'm thinking they should be under the students folder since TaskList are tied to each individual student.

**Comment by tsh4fiq** [comment]
I was thinking we either put it in a separate package altogether or have a task sub-folder under events personally, but I like your idea too @VexingTomahawk
